import Link from 'next/link';import Image from 'next/image';import {notFound} from 'next/navigation';import {resources,articles} from '@/lib/content';import {Breadcrumb,DownloadLink,CopyButton} from '@/components/ui';import PromptBuilder from '@/components/prompt-builder';
export function generateStaticParams(){return resources.map(r=>({slug:r.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const r=resources.find(x=>x.slug===slug);return {title:r?.title,description:r?.desc,alternates:{canonical:'/resources/'+slug+'/'}}}
const sheets:Record<string,{body:string,file:string,article:string}>= {
'cashflow-sheet':{body:'日期｜項目｜收入｜支出｜固定或偶發｜我的觀察\n\n本週收入合計：____\n本週支出合計：____\n本週差額：____\n\n下週想調整的一件事：____',file:'cashflow.csv',article:'cashflow'},
'kids-sheet':{body:'今天的零用錢：____ 元\n\n我想儲蓄：____ 元，因為 ____\n我想花費：____ 元，因為 ____\n我想分享：____ 元，因為 ____\n\n三個罐子的合計：____ 元\n跟家人聊一聊：如果願望改變了，我會怎麼調整？',file:'kids-worksheet.txt',article:'cashflow'},
'automation-sheet':{body:'流程名稱：____\n何時開始：____\n需要的資料：____\n先檢查什麼：____\n完成哪些動作：____\n如何避免重複：____\n失敗時通知誰：____\n人工檢查在哪一步：____\n測試結果：____',file:'automation-worksheet.txt',article:'automation'}};
export default async function Resource({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const r=resources.find(x=>x.slug===slug);if(!r)notFound();const sheet=sheets[slug];return <div className="wrap detail-wrap"><Breadcrumb label="工具包預覽" parent="/resources/" parentLabel="免費工具包"/><section className="resource-hero"><div><span className="tag">免費 · {r.kind}</span><h1>{r.title}</h1><p className="lead">{r.desc}</p><p className="meta">{slug==='ai-guide'?'作者：Ken 季秉澤 · PDF · 約 274 KB':'AK 編輯整理 · 2026 年 10 月 5 日'}</p><a href="#preview" className="button secondary">先看裡面有什麼</a></div><Image src={r.image} width={230} height={320} alt={r.title} className="toolkit-cover"/></section>
<div className="reader-surface" id="preview">{slug==='ai-guide'?<><span className="tag">內容預覽</span><h2>先把一個需求說清楚</h2><p>這份地圖從五個基本功開始：說清楚需求、核對資訊、串起流程、人工修改，以及保存可重用的成果。</p><div className="steps"><p><b>01</b> 選一件每天會做的小事</p><p><b>02</b> 寫下任務、受眾與限制</p><p><b>03</b> 試做、檢查、留下自己的模板</p></div><h3>先試這段填空提示詞</h3><pre className="prompt-output">{articles[0].exercise}</pre><CopyButton text={articles[0].exercise}/><h3>你的 7 天練習</h3><ol><li>挑選一個日常任務。</li><li>寫出目前的工作步驟。</li><li>找出最花時間的一步。</li><li>存下第一版提示詞。</li><li>用三個例子試做。</li><li>檢查資料與來源。</li><li>整理成自己的工作流程。</li></ol><DownloadLink href="/downloads/ai-guide.pdf" name="2026_AI新手實戰地圖_Ken季秉澤.pdf" label="免費下載完整 20 頁 PDF"/><a className="text-link" href="/downloads/ai-guide.pdf" target="_blank" rel="noreferrer">在新視窗閱讀原版 PDF</a><p className="small">上方為手機閱讀摘要，完整排版請開啟原版 PDF。</p></>:slug==='video-prompts'?<><p className="tag">六款原創練習模板</p><PromptBuilder/><hr/><h3>帶走完整工具包</h3><p>包含六款提示詞、三鏡頭分鏡表與成品檢查表。</p><DownloadLink href="/downloads/video-toolkit.md" name="AK_AI影片起步工具包.md"/><details><summary>參考方法與來源</summary><p>參考提示詞分類、分秒敘事與運鏡方法。本站下載內容為 AK 原創練習，未重製第三方完整提示詞。</p><ul><li><a href="https://youmind.com/zh-TW/prompts/video" target="_blank" rel="noreferrer">YouMind 影片提示詞庫</a></li><li><a href="https://generateprompt.net/video-prompts" target="_blank" rel="noreferrer">GeneratePrompt 影片提示詞庫</a></li><li><a href="https://www.videotoprompt.app/trending-prompts" target="_blank" rel="noreferrer">VideoToPrompt 精選提示詞</a></li></ul></details></>:<><span className="tag">先在線上看內容</span><h2>一張表，開始一個小練習</h2><pre className="prompt-output">{sheet.body}</pre><CopyButton text={sheet.body} label="複製練習表"/><DownloadLink href={'/downloads/'+sheet.file} name={'AK_'+r.title+(sheet.file.endsWith('csv')?'.csv':'.txt')}/><p className="small">資料留在你自己的檔案裡，本站不收集填寫結果。</p><Link className="text-link" href={slug==='kids-sheet'?'/kids/':'/learn/'+sheet.article+'/'}>先看使用教學 →</Link></> }</div><section className="section"><h2>拿到工具包，接著做什麼？</h2><p>先完成一個小練習，保留第一次的結果，再改一個地方試試看。</p><Link className="button secondary" href={slug==='ai-guide'?'/learn/ask-ai/':slug==='kids-sheet'?'/kids/':'/learn/'}>開始第一個練習</Link><Link className="text-link" href="/resources/">探索其他工具包 →</Link></section></div>}
