'use client';
import {useEffect,useRef} from 'react';
export const tileColors:Record<string,number>={start:0x8fe08a,save:0x5bd7e8,spend:0xf0c276,share:0xa8b9ff,chance:0xf6edda};
// 16 tiles around a 5×5 square, starting at the front-left corner and moving clockwise from the viewer
const tileXZ=(i:number)=>{const k=i%4,d=1.5;const p=[[-2+k,2],[2,2-k],[2-k,-2],[-2,-2+k]][Math.floor(i/4)];return [p[0]*d,p[1]*d] as const};
export default function Board3D({types,pos,onFail}:{types:string[];pos:number;onFail:()=>void}){const root=useRef<HTMLDivElement>(null);const target=useRef(pos);const failRef=useRef(onFail);failRef.current=onFail;
useEffect(()=>{target.current=pos},[pos]);
useEffect(()=>{if(!root.current)return;let disposed=false;let cleanup=()=>{};import('three').then(T=>{if(disposed||!root.current)return;let renderer:import('three').WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true})}catch{failRef.current();return;}const host=root.current;const H=340;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,H);host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','存存環島大冒險的三維棋盤');const scene=new T.Scene();const camera=new T.PerspectiveCamera(40,host.clientWidth/H,.1,100);camera.position.set(0,11,11);camera.lookAt(0,-.6,0);scene.add(new T.HemisphereLight(0xbdecff,0x123756,3));const sun=new T.DirectionalLight(0xffd8a0,4);sun.position.set(4,8,6);scene.add(sun);const group=new T.Group();scene.add(group);
const mesh=(g:import('three').BufferGeometry,c:number,x:number,y:number,z:number)=>{const m=new T.Mesh(g,new T.MeshStandardMaterial({color:c,roughness:.5,metalness:.15}));m.position.set(x,y,z);group.add(m);return m;};
mesh(new T.BoxGeometry(7.6,.5,7.6),0x244c61,0,-.45,0);mesh(new T.BoxGeometry(4.2,.12,4.2),0x7db5a4,0,-.14,0);
types.forEach((t,i)=>{const [x,z]=tileXZ(i);mesh(new T.BoxGeometry(1.32,.16,1.32),tileColors[t],x,-.1,z);if(t==='chance'){const s=mesh(new T.OctahedronGeometry(.22),0xf1bd62,x,.2,z);s.rotation.y=Math.PI/4}});
// centre: the dream gift and three jars
mesh(new T.BoxGeometry(1,.8,1),0xe46f7a,0,.3,0);mesh(new T.BoxGeometry(1.04,.14,.22),0xf6edda,0,.32,0);mesh(new T.BoxGeometry(.22,.84,1.04),0xf6edda,0,.3,0);[-1.3,1.3].forEach((x,i)=>{mesh(new T.CylinderGeometry(.3,.28,.6,20),[0x5bd7e8,0xa8b9ff][i],x,.15,.9);mesh(new T.CylinderGeometry(.33,.33,.08,20),0xf6edda,x,.48,.9)});for(let i=0;i<4;i++){const x=[-1.2,1.2,-1.4,1.4][i],z=[-1.2,-1.2,-.1,-.1][i];mesh(new T.CylinderGeometry(.06,.09,.4,6),0xb79972,x,.05,z);mesh(new T.ConeGeometry(.3,.8,7),0x386f63,x,.55,z)}
const pawn=new T.Group();const pm=new T.MeshStandardMaterial({color:0xf1bd62,roughness:.3,metalness:.5});pawn.add(new T.Mesh(new T.CylinderGeometry(.18,.32,.55,20),pm));const head=new T.Mesh(new T.SphereGeometry(.2,20,16),pm);head.position.y=.4;pawn.add(head);group.add(pawn);
let shown=target.current;let from=tileXZ(shown);let to=from;let t0=0;const place=(x:number,z:number,lift:number)=>pawn.position.set(x,.32+lift,z);place(from[0],from[1],0);
const observer=new ResizeObserver(()=>{renderer.setSize(host.clientWidth,H);camera.aspect=host.clientWidth/H;camera.updateProjectionMatrix()});observer.observe(host);let visible=true;const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting});io.observe(host);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let id=0;
const draw=(time:number)=>{if(shown!==target.current&&time-t0>260){if(reduced){shown=target.current;from=to=tileXZ(shown)}else{from=to;shown=(shown+1)%16;to=tileXZ(shown)}t0=time}const p=reduced?1:Math.min(1,(time-t0)/260);place(from[0]+(to[0]-from[0])*p,from[1]+(to[1]-from[1])*p,Math.sin(p*Math.PI)*.45);if(visible&&!document.hidden)renderer.render(scene,camera);id=requestAnimationFrame(draw)};id=requestAnimationFrame(draw);
cleanup=()=>{cancelAnimationFrame(id);observer.disconnect();io.disconnect();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove()}}).catch(()=>failRef.current());return()=>{disposed=true;cleanup()}},[types]);
return <div ref={root} className="island-canvas board-canvas"/>}
