'use client';import {useMemo,useState} from 'react';import {Dices,RotateCcw,Plus,Minus,Check,X} from 'lucide-react';import CityBoard3D from './city-board-3d';
import {tiles,characters,chanceCards,riskCards,defaultPlayers,districtCss,typeLabel,typeShort,SALARY,LIVING,START_CASH,QUIZ_REWARD,type CharId,type Card} from '@/lib/city-game';
import {quiz,levels,type Level,type QuizItem} from '@/lib/animal-city-quiz';
type Player={role:string;char:CharId;level:Level;pos:number;cash:number;deposit:number;shops:number[];green:boolean;insured:boolean;happy:number;laps:number;used:number[]};
type Ev={kind:'settle'}|{kind:'tile'}|{kind:'card';card:Card;deck:string}|{kind:'quiz';q:QuizItem;order:number[];picked:number|null};
const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
const shuffle=<T,>(a:T[])=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const rate=(p:Player)=>p.char==='sloth'?.15:.1;
const passive=(p:Player)=>p.shops.reduce((s,i)=>s+(tiles[i].rent??0),0)+(p.green?tiles[21].amount!:0);
const priceFor=(p:Player,i:number)=>Math.round((tiles[i].price??0)*(p.char==='fox'?.8:1));
const worth=(p:Player)=>p.cash+p.deposit+p.shops.reduce((s,i)=>s+(tiles[i].price??0),0)+(p.green?tiles[21].price!:0);
const fresh=(s:{role:string;char:CharId;level:Level}):Player=>({...s,pos:0,cash:START_CASH,deposit:0,shops:[],green:false,insured:false,happy:0,laps:0,used:[]});
export default function CityGame(){const [setup,setSetup]=useState(defaultPlayers);const [rounds,setRounds]=useState(8);const [players,setPlayers]=useState<Player[]|null>(null);const [turn,setTurn]=useState(0);const [round,setRound]=useState(1);const [dice,setDice]=useState<[number,number]|null>(null);const [queue,setQueue]=useState<Ev[]>([]);const [moving,setMoving]=useState(false);const [note,setNote]=useState('');const [over,setOver]=useState(false);const [failed,setFailed]=useState(false);
const owners=useMemo(()=>tiles.map((_,i)=>{const o=players?.find(p=>p.shops.includes(i));return o?characters[o.char].color:null}),[players]);
const pawns=useMemo(()=>(players??[]).map(p=>({pos:p.pos,color:characters[p.char].color})),[players]);
if(!players){const used=setup.map(s=>s.char);const upd=(i:number,v:Partial<typeof setup[number]>)=>setSetup(setup.map((s,k)=>k===i?{...s,...v}:s));
return <div className="city-setup"><p className="muted">2～4 人輪流擲兩顆骰子，每人起始 {START_CASH} 金幣。每經過中央車站結算一次：薪水 {SALARY} ＋店鋪收入＋利息 − 生活費 {LIVING}。</p>
{setup.map((s,i)=><div className="setup-row" key={i}><span className="setup-emoji" aria-hidden="true">{characters[s.char].emoji}</span><label>稱呼<input value={s.role} maxLength={6} onChange={e=>upd(i,{role:e.target.value})}/></label><label>角色<select value={s.char} onChange={e=>upd(i,{char:e.target.value as CharId})}>{(Object.keys(characters) as CharId[]).map(c=><option key={c} value={c} disabled={c!==s.char&&used.includes(c)}>{characters[c].emoji} {characters[c].animal}{characters[c].name}</option>)}</select></label><label>問答等級<select value={s.level} onChange={e=>upd(i,{level:e.target.value as Level})}>{levels.map(l=><option key={l.id} value={l.id}>{l.name}（{l.age}）</option>)}</select></label><p className="small setup-talent">{characters[s.char].talent}</p>{setup.length>2&&<button className="icon-button" aria-label={'移除'+s.role} onClick={()=>setSetup(setup.filter((_,k)=>k!==i))}><Minus size={18}/></button>}</div>)}
<div className="setup-actions">{setup.length<4&&<button className="button secondary" onClick={()=>{const c=(Object.keys(characters) as CharId[]).find(c=>!used.includes(c))!;setSetup([...setup,{role:'玩家'+(setup.length+1),char:c,level:'explorer'}])}}><Plus size={18}/>加一位玩家</button>}<label className="rounds">玩幾輪<select value={rounds} onChange={e=>setRounds(+e.target.value)}>{[6,8,12].map(n=><option key={n} value={n}>{n} 輪（約 {n*setup.length*1.5|0} 分鐘）</option>)}</select></label><button className="button gold-button" onClick={()=>{setPlayers(setup.map(s=>fresh({...s,role:s.role.trim()||characters[s.char].name})));setTurn(0);setRound(1);setDice(null);setQueue([]);setNote('');setOver(false)}}>開始遊戲</button></div></div>}
const me=players[turn];const ch=characters[me.char];const tile=tiles[me.pos];const ev=queue[0];
const setMe=(f:(p:Player)=>Player)=>setPlayers(ps=>ps!.map((p,k)=>k===turn?f(p):p));
const pay=(p:Player,amt:number)=>({...p,cash:Math.max(0,p.cash-amt)});
const done=(msg='')=>{const rest=queue.slice(1);setQueue(rest);if(msg)setNote(msg);if(rest.length===0)endTurn()};
const endTurn=()=>{const n=players.length;const nt=(turn+1)%n;if(nt===0){if(round>=rounds){setOver(true);return}setRound(round+1)}setTurn(nt);setDice(null)};
const roll=()=>{const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);const d=a+b;const to=(me.pos+d)%24;const passed=me.pos+d>=24;setDice([a,b]);setNote('');setMoving(true);setMe(p=>({...p,pos:to}));const q:Ev[]=[];if(passed)q.push({kind:'settle'});if(to!==0)q.push(tileEvent(to));setTimeout(()=>{setMoving(false);setQueue(q);if(q.length===0)endTurn()},d*240+400)};
const tileEvent=(i:number):Ev=>{const t=tiles[i];if(t.type==='chance')return {kind:'card',card:pick(chanceCards),deck:'機會卡'};if(t.type==='risk')return {kind:'card',card:pick(riskCards),deck:'市場風險卡'};if(t.type==='quiz'){const pool=quiz.filter(x=>x.level===me.level&&!me.used.includes(x.id));const q=pick(pool.length?pool:quiz.filter(x=>x.level===me.level));return {kind:'quiz',q,order:shuffle([0,1,2,3]),picked:null}}return {kind:'tile'}};
const settle=()=>{const bonus=me.char==='rabbit'?50:0;const interest=Math.floor(me.deposit*rate(me));const income=SALARY+bonus+passive(me)+interest;const net=income-LIVING;return {bonus,interest,income,net}};
const card=(c:Card)=>{let lose=c.cash&&c.cash<0?-c.cash:0;let msg='';if(c.accident&&lose&&me.insured){msg='保險理賠！這次的損失由保險公司支付。';lose=0;setMe(p=>({...p,insured:false,happy:p.happy+(c.happy??0)}))}else setMe(p=>({...pay(p,lose),cash:Math.max(0,p.cash+(c.cash??0)),happy:p.happy+(c.happy??0)}));done(msg)};
// 結束畫面
if(over){const best=(f:(p:Player)=>number)=>Math.max(...players.map(f));const awards=(p:Player)=>[worth(p)===best(worth)&&'總資產最多',p.deposit===best(x=>x.deposit)&&p.deposit>0&&'最會存錢',passive(p)===best(passive)&&passive(p)>0&&'被動收入最多',p.happy===best(x=>x.happy)&&p.happy>0&&'最暖心市民'].filter(Boolean) as string[];
return <div className="city-over"><h3>{rounds} 輪結束！來看看每個人的城市生活</h3><div className="hud">{players.map((p,k)=><div className="hud-card" key={k} style={{borderColor:characters[p.char].css}}><b>{characters[p.char].emoji} {p.role}</b><span>總資產 <b>{worth(p)}</b></span><span>現金 {p.cash}・存款 {p.deposit}</span><span>店鋪 {p.shops.length} 間・每圈被動收入 {passive(p)}</span><span>幸福點 {p.happy}</span><span className="awards">{(awards(p).length?awards(p):['認真生活獎']).map(a=><em key={a}>🏅{a}</em>)}</span></div>)}</div><div className="completion"><p><b>全家聊一聊：</b>誰的錢最多？誰最快樂？兩個是同一個人嗎？如果再玩一次，你會多買店鋪、多存錢，還是多分享？</p><button className="button primary" onClick={()=>setPlayers(null)}>再玩一局<RotateCcw size={18}/></button></div></div>}
return <div className="city-game"><div className="hud">{players.map((p,k)=><div key={k} className={'hud-card'+(k===turn?' active':'')} style={{borderColor:characters[p.char].css}}><b>{characters[p.char].emoji} {p.role}</b><span>現金 <b>{p.cash}</b></span><span>存款 {p.deposit}・店 {p.shops.length}{p.green?'・🌱':''}{p.insured?'・🛡️':''}</span><span>被動收入 {passive(p)}/圈・幸福 {p.happy}</span></div>)}</div>
<div className="island-box">{!failed&&<CityBoard3D pawns={pawns} active={turn} owners={owners} onFail={()=>setFailed(true)}/>}{failed&&<p className="notice">這台裝置暫時無法顯示 3D，下方的格子路線一樣可以玩。</p>}
<ol className="city-track" aria-label="棋盤 24 格">{tiles.map((t,i)=>{const here=players.filter(p=>p.pos===i);const o=players.find(p=>p.shops.includes(i));return <li key={i} className={'city-cell'+(here.some(p=>p===me)?' here':'')} style={{background:districtCss[t.district],outlineColor:o?characters[o.char].css:undefined}} title={t.name}><span aria-hidden="true">{typeShort[t.type]}</span>{here.length>0&&<span className="cell-pawns" aria-hidden="true">{here.map(p=>characters[p.char].emoji).join('')}</span>}<span className="sr-only">{`第 ${i+1} 格 ${t.name}${o?'，'+o.role+'的店':''}`}</span></li>})}</ol>
<p className="small muted legend">橘＝莽原中心區　金＝金沙廣場　藍＝冰晶鎮　綠＝雨林樹屋區｜店＝店鋪　？＝問答　★＝機會　！＝風險　銀＝銀行　保＝保險　愛＝分享　綠＝綠能　工＝打工　費＝支出</p></div>
<div className="turn-bar" aria-live="polite"><span>第 <b>{round}</b> / {rounds} 輪</span><span>輪到 <b style={{color:ch.css}}>{ch.emoji} {me.role}</b></span></div>
{!ev&&<div className="board-actions"><button className="button gold-button" onClick={roll} disabled={moving}><Dices size={22}/>{moving?'移動中…':`${me.role}擲骰子`}</button></div>}
{dice!==null&&<p className="dice-result">🎲 {dice[0]} ＋ 🎲 {dice[1]} ＝ <b>{dice[0]+dice[1]}</b> 步{!moving&&<>，走到「{tile.name}」</>}</p>}
{note&&!ev&&<p className="board-note" role="status">{note}</p>}
{ev&&!moving&&<div className="event-card" role="dialog" aria-label="事件">{ev.kind==='settle'?(()=>{const s=settle();return <><span className="tag">萬獸中央車站・一圈結算</span><p><b>{me.role}</b> 繞完一圈！</p><ul className="settle"><li>薪水（主動收入）<b>+{SALARY}</b></li>{s.bonus>0&&<li>勤奮獎金 <b>+{s.bonus}</b></li>}<li>店鋪與綠能（被動收入）<b>+{passive(me)}</b></li><li>銀行利息 <b>+{s.interest}</b></li><li>生活費 <b>−{LIVING}</b></li><li className="net">這一圈淨現金流 <b>{s.net>=0?'+':''}{s.net}</b></li></ul><button className="button primary" onClick={()=>{setMe(p=>({...p,cash:Math.max(0,p.cash+s.net),laps:p.laps+1}));done()}}>領取</button></>})()
:ev.kind==='card'?<><span className="tag">{ev.deck}</span><p>{ev.card.text}</p>{ev.card.lesson&&<p className="small"><b>財商小知識：</b>{ev.card.lesson}</p>}{ev.card.accident&&me.insured&&<p className="small">🛡️ 你有保險！</p>}<button className="button primary" onClick={()=>card(ev.card)}>知道了</button></>
:ev.kind==='quiz'?<><span className="tag">財商問答・{levels.find(l=>l.id===me.level)!.name}</span><p><b>{ev.q.title}</b></p><p>{ev.q.story}</p><p><b>{ev.q.q}</b></p><div className="event-choices">{ev.order.map(oi=><button key={oi} className={'button secondary'+(ev.picked!==null?(oi===ev.q.answer?' right':oi===ev.picked?' wrong':''):'')} disabled={ev.picked!==null} onClick={()=>{const ok=oi===ev.q.answer;setQueue([{...ev,picked:oi},...queue.slice(1)]);setMe(p=>({...p,cash:p.cash+(ok?QUIZ_REWARD:0),used:[...p.used,ev.q.id]}))}}>{ev.q.options[oi]}{ev.picked!==null&&oi===ev.q.answer&&<Check size={18}/>}{ev.picked===oi&&oi!==ev.q.answer&&<X size={18}/>}</button>)}</div>{ev.picked!==null&&<><p className="small"><b>{ev.picked===ev.q.answer?`答對了！+${QUIZ_REWARD} 金幣。`:'差一點！'}</b>{ev.q.explain}</p><p className="small"><b>和家人聊聊：</b>{ev.q.talk}</p><button className="button primary" onClick={()=>done()}>繼續</button></>}</>
:<TileEvent/>}</div>}
<p className="small muted">學習用的虛擬金幣，不涉及金錢交易，也不記錄任何資料。遊戲情境不是投資建議。</p></div>;
function TileEvent(){const t=tile;const i=me.pos;
if(t.type==='shop'){const owner=players!.find(p=>p.shops.includes(i));const price=priceFor(me,i);
if(!owner)return <><span className="tag">{t.district}・店鋪</span><p><b>{t.name}</b> 正在出售：{price} 金幣{me.char==='fox'&&'（阿狸 8 折）'}。買下後，每次經過中央車站可收 {t.rent} 金幣，別人停在這裡也要付你 {t.rent} 金幣。</p><div className="event-choices"><button className="button secondary" disabled={me.cash<price} onClick={()=>{setMe(p=>({...p,cash:p.cash-price,shops:[...p.shops,i]}));done(`${me.role}買下了${t.name}！`)}}>買下（−{price}）</button><button className="button secondary" onClick={()=>done('先不買，把錢留著。')}>先不買</button></div>{me.cash<price&&<p className="small">現金不夠。可以先存錢，下次再來。</p>}</>;
if(owner===me)return <><span className="tag">{t.district}・你的店</span><p>這是你的 <b>{t.name}</b>，生意很好！</p><button className="button primary" onClick={()=>done()}>繼續</button></>;
const amt=Math.min(t.rent!,me.cash);return <><span className="tag">{t.district}・{owner.role}的店</span><p>你在 <b>{owner.role}</b> 的 <b>{t.name}</b> 消費，付 {amt} 金幣給店主。</p>{amt<t.rent!&&<p className="small">現金不夠，只付得出 {amt} 金幣。手邊要留一點現金才安心！</p>}<button className="button primary" onClick={()=>{const oi=players!.indexOf(owner);setPlayers(ps=>ps!.map((p,k)=>k===turn?{...p,cash:p.cash-amt}:k===oi?{...p,cash:p.cash+amt}:p));done()}}>付款</button></>}
if(t.type==='bill')return <><span className="tag">{t.district}・支出</span><p>要繳 <b>{t.name}</b> {t.amount} 金幣。這是每個家庭都有的固定支出。</p><button className="button primary" onClick={()=>{setMe(p=>pay(p,t.amount!));done()}}>繳費</button></>;
if(t.type==='work')return <><span className="tag">{t.district}・打工</span><p>在 <b>{t.name}</b> 值班一天，賺到 {t.amount} 金幣。</p><button className="button primary" onClick={()=>{setMe(p=>({...p,cash:p.cash+t.amount!}));done()}}>領薪水</button></>;
if(t.type==='bank')return <><span className="tag">冰晶銀行</span><p>現金 {me.cash}・存款 {me.deposit}。存在這裡的錢，每圈有 {Math.round(rate(me)*100)}% 利息，而且不會被意外花掉。</p><div className="event-choices">{[100,200].map(a=><button key={a} className="button secondary" disabled={me.cash<a} onClick={()=>setMe(p=>({...p,cash:p.cash-a,deposit:p.deposit+a}))}>存 {a}</button>)}<button className="button secondary" disabled={me.deposit===0} onClick={()=>setMe(p=>({...p,cash:p.cash+p.deposit,deposit:0}))}>全部領出</button></div><button className="button primary" onClick={()=>done()}>好了</button></>;
if(t.type==='insure')return me.insured?<><span className="tag">冰晶保險公司</span><p>你已經有保險了 🛡️</p><button className="button primary" onClick={()=>done()}>繼續</button></>:<><span className="tag">冰晶保險公司</span><p>付 {t.amount} 金幣買一份意外險：下次遇到「意外」卡（像修理費），由保險公司幫你付。</p><div className="event-choices"><button className="button secondary" disabled={me.cash<t.amount!} onClick={()=>{setMe(p=>({...p,cash:p.cash-t.amount!,insured:true}));done('買了保險，安心多了！')}}>買保險（−{t.amount}）</button><button className="button secondary" onClick={()=>done()}>不用了</button></div></>;
if(t.type==='share'){const extra=me.char==='cheetah'?1:0;return <><span className="tag">雨林・愛心角</span><p>纜車站在募集愛心，幫助生病的小動物。你想怎麼幫忙？</p><div className="event-choices"><button className="button secondary" disabled={me.cash<t.amount!} onClick={()=>{setMe(p=>({...pay(p,t.amount!),happy:p.happy+2+extra}));done(`捐了 ${t.amount} 金幣，幸福點 +${2+extra}`)}}>捐 {t.amount} 金幣（幸福 +{2+extra}）</button><button className="button secondary" onClick={()=>{setMe(p=>({...p,happy:p.happy+1+extra}));done(`當了一天志工，幸福點 +${1+extra}`)}}>當志工，不花錢（幸福 +{1+extra}）</button></div></>}
if(t.type==='green')return me.green?<><span className="tag">雨林・綠色小農場</span><p>你的小農場長得很好，每圈都有 {t.amount} 金幣收入 🌱</p><button className="button primary" onClick={()=>done()}>繼續</button></>:<><span className="tag">雨林・綠色小農場</span><p>投資 {t.price} 金幣開一座有機小農場，之後每圈多 {t.amount} 金幣被動收入，也讓雨林更健康。</p><div className="event-choices"><button className="button secondary" disabled={me.cash<t.price!} onClick={()=>{setMe(p=>({...p,cash:p.cash-t.price!,green:true}));done('開了綠色小農場！')}}>投資（−{t.price}）</button><button className="button secondary" onClick={()=>done()}>先不要</button></div></>;
return <><p>{t.name}</p><button className="button primary" onClick={()=>done()}>繼續</button></>}}
