'use client';import {useState} from 'react';import {PiggyBank,ShoppingBag,Heart,Plus,Minus,RotateCcw,Check} from 'lucide-react';import Island from './island';
const jars=[{name:'存給未來',desc:'留給一個想完成的願望',icon:PiggyBank,color:'#5bd7e8'},{name:'今天花費',desc:'選擇今天需要的東西',icon:ShoppingBag,color:'#f0c276'},{name:'分享心意',desc:'為在乎的人做一件小事',icon:Heart,color:'#a8b9ff'}];
type Coins=number[];
const missions:{id:string;title:string;story:string;goal:string;need:(c:Coins)=>string[];done:string;ask:string}[]=[
{id:'free',title:'任務 1：自由分配',story:'今天你有 10 枚金幣，可以自己決定怎麼用。',goal:'把 10 枚金幣都放進罐子裡。',need:()=>[],done:'10 枚金幣，都有自己的任務了！',ask:'跟家人說說：你為什麼這樣分？明天想要調整嗎？'},
{id:'book',title:'任務 2：存錢買故事書',story:'你很想要一本故事書，要 4 枚金幣，下星期才會去書店。',goal:'「存給未來」至少放 4 枚。',need:c=>c[0]<4?[`「存給未來」還差 ${4-c[0]} 枚`]:[],done:'下星期就能把故事書帶回家了！',ask:'如果今天先把金幣都花掉，下星期到了書店會發生什麼事？'},
{id:'birthday',title:'任務 3：好朋友的生日',story:'好朋友下星期生日，你想做一張卡片，材料要 2 枚金幣；今天放學也想買 1 枚金幣的點心。',goal:'「分享心意」至少 2 枚，「今天花費」至少 1 枚。',need:c=>[...(c[2]<2?[`「分享心意」還差 ${2-c[2]} 枚`]:[]),...(c[1]<1?['「今天花費」還差 1 枚']:[])],done:'卡片和點心都安排好了，剩下的也有去處！',ask:'送禮物一定要花很多錢嗎？還有哪些不用花錢的心意？'}];
export default function KidsGame(){const [m,setM]=useState(0);const [coins,setCoins]=useState<Coins>([0,0,0]);const [cleared,setCleared]=useState<string[]>([]);const left=10-coins.reduce((a,b)=>a+b,0);const mission=missions[m];const missing=mission.need(coins);const ok=left===0&&missing.length===0;
const add=(i:number,d:number)=>{const next=coins.map((n,k)=>k===i?n+d:n);setCoins(next);if(next.reduce((a,b)=>a+b,0)===10&&mission.need(next).length===0&&!cleared.includes(mission.id))setCleared([...cleared,mission.id])};
const pick=(i:number)=>{setM(i);setCoins([0,0,0])};
return <><section id="island" aria-labelledby="g-island"><h2 id="g-island" className="game-title">遊戲一：3D 存存夢想島</h2><p className="muted">轉一轉夢想島。下方遊戲二放進罐子的金幣，會疊在島上同顏色的罐子上。</p><Island coins={coins}/></section><section id="jars" aria-labelledby="g-jars"><h2 id="g-jars" className="game-title">遊戲二：三個小罐子任務</h2><div className="chips" role="group" aria-label="選擇任務">{missions.map((x,i)=><button key={x.id} className={i===m?'active':''} aria-pressed={i===m} onClick={()=>pick(i)}>{cleared.includes(x.id)&&<Check size={16} aria-label="已完成"/>}{x.title.split('：')[0]}</button>)}</div>
<div className="mission"><span className="tag">{mission.title}</span><p>{mission.story}</p><p className="mission-goal"><b>目標：</b>{mission.goal}</p></div>
<div className="game"><div className="game-heading"><div><span className="eyebrow">今天，你有 10 枚金幣</span><h2>你想怎麼分配？</h2></div><span className="coin-counter" aria-live="polite">剩下 <b>{left}</b> 枚</span></div><div className="jar-grid">{jars.map((j,i)=><div className="jar" key={j.name}><j.icon size={38} color={j.color}/><h3>{j.name}</h3><p>{j.desc}</p><div className="jar-controls"><button className="icon-button" disabled={coins[i]===0} aria-label={'從'+j.name+'拿回一枚金幣'} onClick={()=>add(i,-1)}><Minus/></button><output aria-label={j.name+'金幣數'}>{coins[i]}</output><button className="icon-button" disabled={left===0} aria-label={'放一枚金幣到'+j.name} onClick={()=>add(i,1)}><Plus/></button></div></div>)}</div>
{ok&&<div className="completion" role="status"><h3>{mission.done}</h3><p>{mission.ask}</p>{m<missions.length-1&&<button className="button primary" onClick={()=>pick(m+1)}>挑戰下一個任務</button>}</div>}
{left===0&&!ok&&<div className="hint" role="status"><h3>差一點點！</h3><p>{missing.join('，')}。想一想，要從哪個罐子拿回來？</p></div>}
<button className="button secondary" onClick={()=>setCoins([0,0,0])}>重新分配<RotateCcw size={18}/></button><p className="small muted">這是學習用的虛擬金幣，不涉及金錢交易。離開或重新整理頁面後會重設。</p></div></section></>}
