'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Home,BookOpen,FolderDown,Compass,Search,ArrowUpRight,ChevronRight} from 'lucide-react';
import {useState} from 'react';
export function Header(){return <header className="header"><Link className="brand" href="/" aria-label="AK Wealth Global 首頁"><span className="monogram">AK</span><span>AK WEALTH<br className="mobile-br"/> GLOBAL</span></Link><nav className="desktop-nav"><Link href="/learn/">學習知識庫</Link><Link href="/resources/">免費工具包</Link><Link href="/kids/">親子探索</Link><Link href="/about/">關於我們</Link></nav><Link href="/learn/#search" className="icon-button" aria-label="搜尋知識庫"><Search size={23}/></Link></header>}
const nav=[{href:'/',label:'首頁',icon:Home},{href:'/learn/',label:'學習',icon:BookOpen},{href:'/resources/',label:'工具包',icon:FolderDown},{href:'/kids/',label:'探索',icon:Compass}];
export function BottomNav(){const path=usePathname();return <nav className="bottom-nav" aria-label="主要導覽">{nav.map(n=><Link key={n.href} href={n.href} aria-current={(n.href==='/'?path==='/':path.startsWith(n.href)||n.href==='/learn/'&&['/ai/','/money/'].some(p=>path.startsWith(p)))?'page':undefined}><n.icon size={23}/><span>{n.label}</span></Link>)}</nav>}
export function Footer(){return <footer className="footer"><Link className="brand" href="/"><span className="monogram">AK</span><span>AK WEALTH GLOBAL</span></Link><p>學會用 AI，練習看懂錢。<br/>讓每一次學習，都能用在生活裡。</p><div className="footer-links"><Link href="/about/">關於我們</Link><Link href="/privacy/">隱私說明</Link><a href="https://ak-wealth-global.kit.com/" target="_blank" rel="noreferrer">品牌資訊 <ArrowUpRight size={14}/></a></div><small>© 2026 AK Wealth Global · 財商內容僅供教育用途。</small></footer>}
export function CopyButton({text,label='複製提示詞'}:{text:string;label?:string}){const [status,setStatus]=useState('');return <><button className="button primary" onClick={async()=>{try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text)}else{const field=document.createElement('textarea');field.value=text;field.style.position='fixed';field.style.opacity='0';document.body.appendChild(field);field.select();const copied=document.execCommand('copy');field.remove();if(!copied)throw new Error('copy failed')}setStatus('已複製，可以貼到你使用的工具。')}catch{setStatus('複製未成功，請長按提示詞或練習文字手動複製。')}}}>{label}<ChevronRight size={20}/></button><p role="status" className="status">{status}</p></>}
export function DownloadLink({href,name,label='免費下載'}:{href:string;name:string;label?:string}){const [done,setDone]=useState(false);return <><a className="button primary" href={href} download={name} onClick={()=>setDone(true)}>{done?'再次下載':label}<FolderDown size={20}/></a>{done&&<div role="status" className="notice">已送出下載請求。若沒有開始，請再次下載，或<a href={href} target="_blank" rel="noreferrer">開啟檔案</a>。</div>}</>}
export function Breadcrumb({label,parent='/learn/',parentLabel='學習知識庫'}:{label:string;parent?:string;parentLabel?:string}){return <nav className="breadcrumb" aria-label="麵包屑"><Link href="/">首頁</Link><ChevronRight size={14}/><Link href={parent}>{parentLabel}</Link><ChevronRight size={14}/><span>{label}</span></nav>}
